/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.codex.jsonc --env-file=/tmp/learning-threads-codex-types.env --include-runtime=false --env-interface=CodexEnv codex/env.d.ts` (hash: 332fc8fdb58096c12878955158db631a)
interface __BaseEnv_CodexEnv {
	FILES: R2Bucket;
	CODEX_AUTH_ENCRYPTION_KEY: string;
	Sandbox: DurableObjectNamespace<import("./worker").Sandbox>;
	ACCOUNT: DurableObjectNamespace<import("./worker").CodexAccount>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "Sandbox" | "CodexAccount";
	}
	interface Env extends __BaseEnv_CodexEnv {}
}
interface CodexEnv extends __BaseEnv_CodexEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CODEX_AUTH_ENCRYPTION_KEY">> {}
}
